export const users = [
  {
    first_name: "James",
    last_name: "Butt",
    company_name: "Benton, John B Jr",
    address: "6649 N Blue Gum St",
    city: "New Orleans",
    county: "Orleans",
    state: "LA",
    zip: 70116,
    phone1: "504-621-8927",
    phone2: "504-845-1427",
    email: "jbutt@gmail.com",
    web: "http://www.bentonjohnbjr.com",
  },
  {
    first_name: "Josephine",
    last_name: "Darakjy",
    company_name: "Chanay, Jeffrey A Esq",
    address: "4 B Blue Ridge Blvd",
    city: "Brighton",
    county: "Livingston",
    state: "MI",
    zip: 48116,
    phone1: "810-292-9388",
    phone2: "810-374-9840",
    email: "josephine_darakjy@darakjy.org",
    web: "http://www.chanayjeffreyaesq.com",
  },
  {
    first_name: "Art",
    last_name: "Venere",
    company_name: "Chemel, James L Cpa",
    address: "8 W Cerritos Ave #54",
    city: "Bridgeport",
    county: "Gloucester",
    state: "NJ",
    zip: "08014",
    phone1: "856-636-8749",
    phone2: "856-264-4130",
    email: "art@venere.org",
    web: "http://www.chemeljameslcpa.com",
  },
  {
    first_name: "Lenna",
    last_name: "Paprocki",
    company_name: "Feltz Printing Service",
    address: "639 Main St",
    city: "Anchorage",
    county: "Anchorage",
    state: "AK",
    zip: 99501,
    phone1: "907-385-4412",
    phone2: "907-921-2010",
    email: "lpaprocki@hotmail.com",
    web: "http://www.feltzprintingservice.com",
  },
  {
    first_name: "Donette",
    last_name: "Foller",
    company_name: "Printing Dimensions",
    address: "34 Center St",
    city: "Hamilton",
    county: "Butler",
    state: "OH",
    zip: 45011,
    phone1: "513-570-1893",
    phone2: "513-549-4561",
    email: "donette.foller@cox.net",
    web: "http://www.printingdimensions.com",
  },
  {
    first_name: "Simona",
    last_name: "Morasca",
    company_name: "Chapman, Ross E Esq",
    address: "3 Mcauley Dr",
    city: "Ashland",
    county: "Ashland",
    state: "OH",
    zip: 44805,
    phone1: "419-503-2484",
    phone2: "419-800-6759",
    email: "simona@morasca.com",
    web: "http://www.chapmanrosseesq.com",
  },

  {
    first_name: "Janey",
    last_name: "Gabisi",
    company_name: "Dobscha, Stephen F Esq",
    address: "40 Cambridge Ave",
    city: "Madison",
    county: "Dane",
    state: "WI",
    zip: 53715,
    phone1: "608-967-7194",
    phone2: "608-586-6912",
    email: "jgabisi@hotmail.com",
    web: "http://www.dobschastephenfesq.com",
  },
  {
    first_name: "Lili",
    last_name: "Paskin",
    company_name: "Morgan Custom Homes",
    address: "20113 4th Ave E",
    city: "Kearny",
    county: "Hudson",
    state: "NJ",
    zip: "07032",
    phone1: "201-431-2989",
    phone2: "201-478-8540",
    email: "lili.paskin@cox.net",
    web: "http://www.morgancustomhomes.com",
  },
  {
    first_name: "Loren",
    last_name: "Asar",
    company_name: "Olsen Payne & Company",
    address: "6 Ridgewood Center Dr",
    city: "Old Forge",
    county: "Lackawanna",
    state: "PA",
    zip: 18518,
    phone1: "570-648-3035",
    phone2: "570-569-2356",
    email: "loren.asar@aol.com",
    web: "http://www.olsenpaynecompany.com",
  },
  {
    first_name: "Dorothy",
    last_name: "Chesterfield",
    company_name: "Cowan & Kelly",
    address: "469 Outwater Ln",
    city: "San Diego",
    county: "San Diego",
    state: "CA",
    zip: 92126,
    phone1: "858-617-7834",
    phone2: "858-732-1884",
    email: "dorothy@cox.net",
    web: "http://www.cowankelly.com",
  },
  {
    first_name: "Gail",
    last_name: "Similton",
    company_name: "Johnson, Wes Esq",
    address: "62 Monroe St",
    city: "Thousand Palms",
    county: "Riverside",
    state: "CA",
    zip: 92276,
    phone1: "760-616-5388",
    phone2: "760-493-9208",
    email: "gail_similton@similton.com",
    web: "http://www.johnsonwesesq.com",
  },
  {
    first_name: "Catalina",
    last_name: "Tillotson",
    company_name: "Icn Pharmaceuticals Inc",
    address: "3338 A Lockport Pl #6",
    city: "Margate City",
    county: "Atlantic",
    state: "NJ",
    zip: "08402",
    phone1: "609-373-3332",
    phone2: "609-826-4990",
    email: "catalina@hotmail.com",
    web: "http://www.icnpharmaceuticalsinc.com",
  },
  {
    first_name: "Lawrence",
    last_name: "Lorens",
    company_name: "New England Sec Equip Co Inc",
    address: "9 Hwy",
    city: "Providence",
    county: "Providence",
    state: "RI",
    zip: "02906",
    phone1: "401-465-6432",
    phone2: "401-893-1820",
    email: "lawrence.lorens@hotmail.com",
    web: "http://www.newenglandsecequipcoinc.com",
  },
  {
    first_name: "Carlee",
    last_name: "Boulter",
    company_name: "Tippett, Troy M Ii",
    address: "8284 Hart St",
    city: "Abilene",
    county: "Dickinson",
    state: "KS",
    zip: 67410,
    phone1: "785-347-1805",
    phone2: "785-253-7049",
    email: "carlee.boulter@hotmail.com",
    web: "http://www.tippetttroymii.com",
  },
  {
    first_name: "Thaddeus",
    last_name: "Ankeny",
    company_name: "Atc Contracting",
    address: "5 Washington St #1",
    city: "Roseville",
    county: "Placer",
    state: "CA",
    zip: 95678,
    phone1: "916-920-3571",
    phone2: "916-459-2433",
    email: "tankeny@ankeny.org",
    web: "http://www.atccontracting.com",
  },
  {
    first_name: "Jovita",
    last_name: "Oles",
    company_name: "Pagano, Philip G Esq",
    address: "8 S Haven St",
    city: "Daytona Beach",
    county: "Volusia",
    state: "FL",
    zip: 32114,
    phone1: "386-248-4118",
    phone2: "386-208-6976",
    email: "joles@gmail.com",
    web: "http://www.paganophilipgesq.com",
  },
  {
    first_name: "Alesia",
    last_name: "Hixenbaugh",
    company_name: "Kwikprint",
    address: "9 Front St",
    city: "Washington",
    county: "District of Columbia",
    state: "DC",
    zip: 20001,
    phone1: "202-646-7516",
    phone2: "202-276-6826",
    email: "alesia_hixenbaugh@hixenbaugh.org",
    web: "http://www.kwikprint.com",
  },
  {
    first_name: "Lai",
    last_name: "Harabedian",
    company_name: "Buergi & Madden Scale",
    address: "1933 Packer Ave #2",
    city: "Novato",
    county: "Marin",
    state: "CA",
    zip: 94945,
    phone1: "415-423-3294",
    phone2: "415-926-6089",
    email: "lai@gmail.com",
    web: "http://www.buergimaddenscale.com",
  },
  {
    first_name: "Brittni",
    last_name: "Gillaspie",
    company_name: "Inner Label",
    address: "67 Rv Cent",
    city: "Boise",
    county: "Ada",
    state: "ID",
    zip: 83709,
    phone1: "208-709-1235",
    phone2: "208-206-9848",
    email: "bgillaspie@gillaspie.com",
    web: "http://www.innerlabel.com",
  },
  {
    first_name: "Raylene",
    last_name: "Kampa",
    company_name: "Hermar Inc",
    address: "2 Sw Nyberg Rd",
    city: "Elkhart",
    county: "Elkhart",
    state: "IN",
    zip: 46514,
    phone1: "574-499-1454",
    phone2: "574-330-1884",
    email: "rkampa@kampa.org",
    web: "http://www.hermarinc.com",
  },
  {
    first_name: "Flo",
    last_name: "Bookamer",
    company_name: "Simonton Howe & Schneider Pc",
    address: "89992 E 15th St",
    city: "Alliance",
    county: "Box Butte",
    state: "NE",
    zip: 69301,
    phone1: "308-726-2182",
    phone2: "308-250-6987",
    email: "flo.bookamer@cox.net",
    web: "http://www.simontonhoweschneiderpc.com",
  },
  {
    first_name: "Jani",
    last_name: "Biddy",
    company_name: "Warehouse Office & Paper Prod",
    address: "61556 W 20th Ave",
    city: "Seattle",
    county: "King",
    state: "WA",
    zip: 98104,
    phone1: "206-711-6498",
    phone2: "206-395-6284",
    email: "jbiddy@yahoo.com",
    web: "http://www.warehouseofficepaperprod.com",
  },
  {
    first_name: "Chauncey",
    last_name: "Motley",
    company_name: "Affiliated With Travelodge",
    address: "63 E Aurora Dr",
    city: "Orlando",
    county: "Orange",
    state: "FL",
    zip: 32804,
    phone1: "407-413-4842",
    phone2: "407-557-8857",
    email: "chauncey_motley@aol.com",
    web: "http://www.affiliatedwithtravelodge.com",
  },
];
